name: Module Compressor

on:
  push:
    paths:
      - 'module/**'

jobs:
  module_compressor:
    runs: 
      using: 'node20'
      main: 'main.js'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TSupport-Advance#${{ github.run_number }}
          path: module/**
