name: Module Compressor

on:
  push:
    paths:
      - 'module/**'

jobs:
  module_compressor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TSupport-Advance#${{ github.run_number }}
          path: module/**
