name: Zip Release

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version and check duplication
        run: |
          VERSION=$(grep '^version=' modules/module.prop | cut -d'=' -f2)
          TAG_NAME="$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME$"; then
            echo "DUPLICATE=true" >> $GITHUB_ENV
            echo "Warning: Version $TAG_NAME already exist! Aborting process."
          else
            echo "DUPLICATE=false" >> $GITHUB_ENV
          fi

      - name: Update release.json
        if: env.DUPLICATE == 'false'
        run: |
          VERSION=$(grep '^version=' modules/module.prop | cut -d'=' -f2)
          VERSION_CODE=$(grep '^versionCode=' modules/module.prop | cut -d'=' -f2)
          
          ZIP_URL="https://github.com/Citra-Standalone/TSupport-Advance/releases/latest/download/TSupport-Advance-$VERSION.zip"
          
          jq --arg ver "$VERSION" \
             --arg vcode "$VERSION_CODE" \
             --arg url "$ZIP_URL" \
             '.version = $ver | .versionCode = $vcode | .zipUrl = $url' \
             release.json > release.tmp && mv release.tmp release.json

          sed -i "s|^## TSupport-Advance (.*)|## TSupport-Advance ( $VERSION )|" changelog.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if ! git diff --quiet; then
            git add release.json changelog.md
            git commit -m "chore: update release.json to $VERSION ($VERSION_CODE)"
            git push
          else
            echo "No changes detected, skipping commit."
          fi

      - name: Zip specific folders
        if: env.DUPLICATE == 'false'
        run: cd modules && zip -r ../TSupport-Advance-${{ env.VERSION }}.zip *
        
      - name: Prepare Release Body
        if: env.DUPLICATE == 'false'
        shell: python
        run: |
          with open('changelog.md', 'r', encoding='utf-8') as f:
              content = f.read()
          
          with open('supportme.md', 'r', encoding='utf-8') as f:
              support_content = f.read()
          
          import re
          
          new_content = re.sub(r'## Support me.*?---', f'#{support_content}', content, flags=re.DOTALL)
          
          with open('release_body.md', 'w', encoding='utf-8') as f:
              f.write(new_content)

      - name: Create Release
        if: env.DUPLICATE == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          body_path: release_body.md
          files: TSupport-Advance-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
